name: build and upload kernel
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          build-mount-path: /nix
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Sync repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: nix build -L .
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: result/