name: build and cache packages
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Sync repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: nix build -L .