name: build and cache packages
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Sync repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - run: nix build -L .
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: result/